name: ECS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t aws-devops-ecs-app ./app

      - name: Debug Print ECR URL
        run: echo "ECR URL = ${{ secrets.ECR_REPO_URL }}"

      - name: Tag Docker image
        run: |
          echo "Tagging image with ECR URL..."
          docker tag aws-devops-ecs-app:latest ${{ secrets.ECR_REPO_URL }}:latest

      - name: Push Docker image to ECR
        run: |
          echo "Pushing image to ECR..."
          docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Render ECS task definition
        id: taskdef
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: terraform/ecs-task-def.json
          container-name: aws-devops-ecs-app
          image: ${{ secrets.ECR_REPO_URL }}:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: aws-devops-ecs-service
          cluster: aws-devops-ecs-cluster
          wait-for-service-stability: true

